#!/usr/bin/env bash
# Fails when a file credits a tool for the work.
#
# The repository is signed by its maintainers and contributors, so assistant
# names are denied by default. scripts/attribution-allowlist.txt holds the path
# prefixes where such a name is the subject matter rather than a signature: an
# adapter written for that vendor, or the page documenting it.
set -euo pipefail

cd "$(dirname "$0")/.."

# The scans below read the list through a pipe that hides its exit status, so a
# list that could not be made fails here rather than scanning nothing.
scripts/repo-files.sh >/dev/null

readonly ALLOWLIST=scripts/attribution-allowlist.txt
readonly PATTERN='co-authored-by:|generated (with|by) |written (with|by) an? ai|ai[-_ ](generated|assisted|written)|with ai assistance|powered by claude|claude\.ai/code|claude-session|🤖|\b(claude|anthropic|chatgpt|copilot|codex)\b'

allowed() {
	local path=$1 prefix
	while IFS= read -r prefix; do
		case "$prefix" in '' | '#'*) continue ;; esac
		case "$path" in "$prefix"*) return 0 ;; esac
	done <"$ALLOWLIST"
	return 1
}

status=0
while IFS= read -r hit; do
	allowed "${hit%%:*}" && continue
	echo "attribution: $hit" >&2
	status=1
done < <(
	# The check scripts and their allowlists name the strings they forbid.
	scripts/repo-files.sh |
		grep -vE '^scripts/(check-.*\.sh|.*-allowlist\.txt)$' |
		tr '\n' '\0' | xargs -0 grep -inIE "$PATTERN" 2>/dev/null |
		# "Code generated by <tool>. DO NOT EDIT." is the marker Go requires on
		# generated files. It names a compiler, not an author.
		grep -vE '^[^:]+:[0-9]+:// Code generated .* DO NOT EDIT\.$' || true
)

if [ "$status" -ne 0 ]; then
	echo >&2
	echo "This repository credits no tool. Remove the line, or add its path" >&2
	echo "prefix to $ALLOWLIST with a reason." >&2
	exit 1
fi

echo "attribution: clean"
